from tutorials.views.login_views import dashboard
from tutorials.views.login_views import home
from tutorials.views.login_views import LoginProhibitedMixin
from tutorials.views.login_views import LogInView
from tutorials.views.login_views import log_out
from tutorials.views.login_views import PasswordView
from tutorials.views.login_views import ProfileUpdateView
from tutorials.views.login_views import StudentSignUpView
from tutorials.views.login_views import TutorSignUpView
from tutorials.views.booking_views import create_booking
