# Generated by Django 5.1.2 on 2024-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(default='Code Tutors HQ', max_length=100)),
                ('frequency', models.CharField(choices=[('weekly', 'once a week'), ('fortnightly', 'once a fortnight')], default='once a week', max_length=20)),
                ('duration', models.CharField(choices=[('short', '1 hour'), ('long', '2 hours')], default='short', max_length=10)),
            ],
        ),
    ]
