# Generated by Django 5.1.2 on 2024-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('short', '1 hour'), ('long', '2 hours')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'once a week'), ('fortnightly', 'once a fortnight')], max_length=20),
        ),
    ]
