# Generated by Django 5.1.2 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutor_specializes_in_c_tutor_specializes_in_java_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='specializes_in_c',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='specializes_in_sql',
        ),
        migrations.AddField(
            model_name='tutor',
            name='specializes_in_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='specializes_in_SQL',
            field=models.BooleanField(default=False),
        ),
    ]
