# Generated by Django 5.1.2 on 2024-12-09 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter your preferred hourly rate: ', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
