# Generated by Django 5.1.2 on 2024-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_booking_duration_alter_booking_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('fortnightly', 'fortnightly')], max_length=20),
        ),
    ]
