# Generated by Django 5.1.2 on 2024-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_booking_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('short', 'short (1hr)'), ('long', 'long (2hrs)')], max_length=10),
        ),
    ]
