# Generated by Django 5.1.2 on 2024-11-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_student'),
        ('tutorials', '0005_alter_booking_duration'),
    ]

    operations = [
    ]
