# Generated by Django 5.1.2 on 2024-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_booking_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('short', 'short (1hr)'), ('long', 'long (2hrs)')], default='short', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('fortnightly', 'fortnightly')], default='weekly', max_length=20),
        ),
    ]
