# Generated by Django 4.2.16 on 2024-12-02 15:42

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_alter_booking_duration_alter_booking_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specializes_in_python', models.BooleanField(default=False)),
                ('specializes_in_java', models.BooleanField(default=False)),
                ('specializes_in_C', models.BooleanField(default=False)),
                ('specializes_in_ruby', models.BooleanField(default=False)),
                ('specializes_in_SQL', models.BooleanField(default=False)),
                ('available_monday', models.BooleanField(default=False)),
                ('available_tuesday', models.BooleanField(default=False)),
                ('available_wednesday', models.BooleanField(default=False)),
                ('available_thursday', models.BooleanField(default=False)),
                ('available_friday', models.BooleanField(default=False)),
                ('available_saturday', models.BooleanField(default=False)),
                ('available_sunday', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Enter your preferred hourly rate: ', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('tutorials.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
