# Generated by Django 5.1.2 on 2024-12-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorials.tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='students',
            field=models.ManyToManyField(related_name='tutors', through='tutorials.Booking', to='tutorials.student'),
        ),
    ]
