# Generated by Django 5.1.2 on 2024-12-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_booking_tutor_tutor_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='students',
        ),
    ]
